name: time_tracker
description: A Flutter time tracking application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  uuid: ^4.5.1
  firebase_core: ^2.30.0
  firebase_auth: ^4.18.0
  http: ^1.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true