// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqe0-EGtrvAXiUPTFPuiYU8Kwe29e1Rw8',
    appId: '1:140149499548:web:b16689c19d090d6809af59',
    messagingSenderId: '140149499548',
    projectId: 'time-tracker-1c6d8',
    authDomain: 'time-tracker-1c6d8.firebaseapp.com',
    storageBucket: 'time-tracker-1c6d8.firebasestorage.app',
    measurementId: 'G-68CSYEKLCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7H_3bsr8mqYa1IBiW9AJQXHkf6z7fU0I',
    appId: '1:140149499548:android:5cc0cf1ee5d8860f09af59',
    messagingSenderId: '140149499548',
    projectId: 'time-tracker-1c6d8',
    storageBucket: 'time-tracker-1c6d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRkbtUf4Pvi96VdDXnoPIXLBL--pMpwqE',
    appId: '1:140149499548:ios:5de642ca9d0d55f909af59',
    messagingSenderId: '140149499548',
    projectId: 'time-tracker-1c6d8',
    storageBucket: 'time-tracker-1c6d8.firebasestorage.app',
    iosBundleId: 'com.example.timeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRkbtUf4Pvi96VdDXnoPIXLBL--pMpwqE',
    appId: '1:140149499548:ios:5de642ca9d0d55f909af59',
    messagingSenderId: '140149499548',
    projectId: 'time-tracker-1c6d8',
    storageBucket: 'time-tracker-1c6d8.firebasestorage.app',
    iosBundleId: 'com.example.timeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqe0-EGtrvAXiUPTFPuiYU8Kwe29e1Rw8',
    appId: '1:140149499548:web:1d0aafc6f58f86be09af59',
    messagingSenderId: '140149499548',
    projectId: 'time-tracker-1c6d8',
    authDomain: 'time-tracker-1c6d8.firebaseapp.com',
    storageBucket: 'time-tracker-1c6d8.firebasestorage.app',
    measurementId: 'G-SX6ZNRZPQF',
  );
}
